# Generated by Django 2.2.12 on 2021-10-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicaldata',
            name='componentvalue',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clinicaldata',
            name='componentname',
            field=models.CharField(choices=[('hw', 'Height/Weight'), ('bp', 'Blood Pressure'), ('hr', 'Heart Rate')], max_length=10),
        ),
        migrations.AlterField(
            model_name='clinicaldata',
            name='measureddate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
